[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mixa", email = "houseyoupol@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bcrypt==3.2.0",
    "passlib[bcrypt]>=1.7.4",
    "pillow>=12.3.0",
    "pyjwt>=2.15.0",
    "pyotp>=2.10.0",
    "pytest>=9.1.1",
    "qrcode>=8.2",
]
